version: '3'
services:
  mysql:
    image: library/mysql:5.6
    container_name: mysql
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_USER: db
      MYSQL_DATABASE: db
      MYSQL_PASSWORD: db
    ports:
      - "3306:3306"
  php-fpm:
    build:
      context: ./.docker/apache
      dockerfile: ./Dockerfile
    hostname: php-fpm
    volumes:
      - "./:/var/www/html"
      - './.docker/apache/000-default.config:/etc/apache2/sites-available/000-default.conf'
    working_dir: "/var/www/html"
    ports:
      - '80:80'
    links:
      - mysql
    depends_on:
      - mysql
