version: '3'
services:
    mysql:
      image: library/mysql:5.6
      container_name: mysql
      restart: always
      command: "--default-authentication-plugin=mysql_native_password"
      environment:
        MYSQL_ROOT_PASSWORD: db
        MYSQL_USER: db
        MYSQL_DATABASE: db
        MYSQL_PASSWORD: db
      ports:
        - "3306:3306"
    nginx:
      hostname: nginx
      image: webdevops/nginx
      ports:
      - "8080:80"
      volumes:
      - "./:/app"
      environment:
        WEB_DOCUMENT_ROOT: /app
        WEB_DOCUMENT_INDEX: index.html
        WEB_PHP_SOCKET: php-fpm:9000
    php-fpm:
      image: webdevops/php-dev:7.3
      hostname: php-fpm
      volumes:
          - "./:/app"
      working_dir: "/app"
      depends_on:
          - mysql
